sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
before_install:
  - npm i -g npm@latest
script:
  - npm run lint
  - npm run build
after_success:
  - npm run autorelease
branches:
  only:
    - "master"
