sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '4'
before_install:
  - npm i -g npm@latest
after_success:
  - npm run autorelease
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
